### ISSUE TITLE
Missing Back And Forward Buttons

### ISSUE THREAD

**Issue by bananstache** [mimipile/firefoxCSS#2]
I don't know what I did but the back and forward buttons disappeared after restarting Firefox with the theme on.

**Comment by bananstache** [comment]
Nevermind, I didn't read the readme fully

**Comment by mimipile** [comment]
lmao :skull: i'ts fine. I can better clarify it in the readme

**Comment by mimipile** [comment]
done~
7427038110db630abc7c670b6bb4d5d754c13e3d
